# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
