# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_app_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='svn_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='svn_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='svn_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
