# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20161017_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='complete_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task_type',
            field=models.IntegerField(choices=[(0, b'Publish'), (1, b'Backup'), (2, b'Rollback'), (3, b'Startup'), (4, b'Shutdown'), (5, b'DeleteBackup'), (6, b'UnzipWar'), (7, b'CheckApp'), (8, b'GenWarFile')], null=True),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='total_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
