# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20161017_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task_type',
            field=models.IntegerField(choices=[(0, b'Publish'), (1, b'Backup'), (2, b'Rollback'), (3, b'Startup'), (4, b'Shutdown'), (5, b'DeleteBackup'), (6, b'UnzipWar'), (7, b'CheckApp'), (8, b'GenWarFile'), (9, b'RebootApp')], null=True),
        ),
    ]
