# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_server_current_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='check_script_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_script', to='cmdb.Scripts'),
        ),
    ]
