# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20161024_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='app',
        ),
        migrations.RemoveField(
            model_name='logger',
            name='operation',
        ),
        migrations.DeleteModel(
            name='Backup',
        ),
    ]
