# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_auto_20161026_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task_type',
            field=models.IntegerField(blank=True, choices=[(0, b'Publish'), (1, b'Backup'), (2, b'Rollback'), (3, b'Startup'), (4, b'Shutdown'), (5, b'DeleteBackup'), (6, b'UnzipWar'), (7, b'CheckApp'), (8, b'GenWarFile'), (9, b'RebootApp'), (10, b'DeleteRemoteBackup'), (11, b'RollbackFromServer')], null=True),
        ),
    ]
