# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0014_auto_20161026_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='server',
            field=models.ManyToManyField(to='cmdb.Server'),
        ),
    ]
