# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20161026_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='server',
        ),
        migrations.AddField(
            model_name='logger',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server'),
        ),
    ]
