# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0016_auto_20161026_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='username',
            new_name='user',
        ),
    ]
